# hostname (and path) to the root eg. http://spf13.com/
baseurl = "//virgilio.mib.infn.it/~sbarrato/"

# Site title
title = "Tullia Sbarrato"

# Copyright
copyright = "(c) 2015 Tullia Sbarrato."

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "rubin"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "your_disqus_shortname"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Tullia Sbarrato"
    email = "tullia.sbarrato@unimib.it"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    name = "Your name"
  	description = "Describe your website"
    brand = "foobar"
    topline = "few words about your site"
    footline = "code with <i class='fa fa-heart'></i>"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    [params.sidebar]
      # Replace the avatar with a picture of your own under static/images
      avatar = "avatar.jpg"
      # The icons will be shown if you enter your username
      dribbble = ""
      facebook = ""
      linkedin = "tullia-sbarrato-1ba14760" # Your LinkedIn profile ID (from public URL)
      researchgate = "Tullia_Sbarrato"

      copyright = [
        "&copy; Tullia Sbarrato",
        "Design: [HTML5 UP](//html5up.net)",
      ]

    [params.about]
      title = "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque."
      content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
