baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Strata"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Tullia Sbarrato"
	description = "Tullia's personal webpage"

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = ""


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Tullia Sbarrato**<br> Postdoctoral Fellow<br> or ''Assegnista di Ricerca''"
		# The icons will be shown if you enter your username
		twitter = "spf13"
		github = "spf13"
		dribbble = ""
		facebook = ""

		copyright = [
			"&copy; John Doe",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		title = "About Me"
		content = "I am a Postdoc fellow in the [Astrophysics group](http://fisica.mib.infn.it/media/homepages/astrofisica/) of the [Università degli Studi di Milano - Bicocca](www.unimib.it). I obtained my PhD in November 2014 at the [Università degli Studi dell'Insubria](www.uninsubria.it), working at the Brera Observatory ([INAF-OAB](www.brera.inaf.it)) and at the European Southern Observatory ([ESO](www.eso.org)). I collaborate with the [high energy astrophysics group](http://meratehighenergy.blogspot.it/) of INAF-OAB in Merate. My work is focused on **Active Galactic Nuclei**. I am currently studying the highest redshift quasars known, to understand how the most massive black holes in the early Universe could form in their (very) short life-time. The main part of my work is devoted to blazars. Thanks to their peculiar orientation, they are the perfect tools to study the role of jets in the physics of Active Galactic Nuclei."


	[params.portfolio]
		title = "About My Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		title = "Get In Touch"
		content = "A few ways to contact me"

		address = [
			"Università degli Studi di Milano - Bicocca",
			"Dipartimento di Fisica ``G. Occhialini''",
			"piazza della Scienza 3, 20126 Milano, Italy"
		]
		phone = "+39 02 6448 2350"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "tullia.sbarrato@unimib.it"

		#[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
		#	name = "Name"
		#	email = "Email"
		#	message = "Message"
		#	submit = "Send message"