baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "your blog title"

[author]
name = "Tullia Sbarrato"
# email will use for gravatar
email = "tullia.sbarrato@unimib.it"

[taxonomies]
category = "categories"

[params]
# site description, will show under navigation
description = ""

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss = "/index.xml"
subscribe_email = ""

# social links
facebook_user = ""
googleplus_user = ""
twitter_user = ""
github_user = ""
coderwall_user = ""
stackoverflow_user = ""
stackoverflow_user_id = ""
linkedin_user = ""
pinterest_user = ""
delicious_user = ""
pinboard_user = ""
quora_user = ""
instagram_user = ""
behance_user = ""
douban_user = ""

# share links
facebook_like = true
twitter_tweet_button = true
google_plus_one = "true"
addthis_profile_id = ""

# Disqus Comments
disqus_short_name = ""
disqus_show_comment_count = false

# google analytics
google_analytics_tracking_id = ""